# Default application configuration that all configurations inherit from.

exclude: "node_modules/**"

linters:
  EmptyLineBetweenBlocks:
    enabled: false

  ImportantRule:
    exclude:
      - "app/assets/stylesheets/**"

  NestingDepth:
    enabled: false

  SelectorDepth:
    enabled: false

  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: true

  StringQuotes:
    enabled: true
    style: double_quotes
