# Application configuration

default: &default
  title: "UNBOXED - All you need is Code"
  description: "Search for a GitHub user and find out the favourite programming language based on her/his open source projects."
  twitter_username: "@iigethr"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
