# Application configuration

default: &default
  title: "All you need is Code"
  description: "There's nothing you can do that can't be coded."
  twitter_username: "@ubxd"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
